#################################
# List of simulation parameters #
#################################

#### PARAMETERS TO BE MANUALLY INSERTED ####
# Number of tests for each master
N_TEST=100 
# Clock period in ns
CLK_PERIOD=50
# Number of clock cycles after which the reset signal is deasserted
RST_CLK_CYCLES=10

#### PARAMETERS AUTOMATICALLY GENERATED BY THE MAKEFILE ####
# If you need to change these values for advanced 
# verification purposes, avoid using the "setup" targets of the makefile,
# as they will overwrite these parameters

# Flag for the random generation of the gnt signal (TCDM side)
RANDOM_GNT=1
# Flag to activate the priority handling check
PRIORITY_CHECK=1
# Maximum cycle offset: needed if you want to generate the list of the transaction with masters_main.py. It indicates the maximum number of clock cycles 
# between two consecutive requests coming from the same master. Note: the minimum value for this parameter is 1.
MAX_CYCLE_OFFSET=7