#################################
# List of simulation parameters #
#################################

#### PARAMETERS TO BE MANUALLY INSERTED ####
# Number of tests for each master in the log branch
N_TEST=1000
# Ratio between the number of tests for a master in the hwpe branch and log branch
TEST_RATIO=1
# Clock period in ns
CLK_PERIOD=50
# Number of clock cycles after which the reset signal is deasserted
RST_CLK_CYCLES=10
#Maximum expected number of cycles between the gnt signal and the r_valid signal
MAX_CYCLES_BETWEEN_GNT_RVALID=1

#### PARAMETERS AUTOMATICALLY GENERATED BY THE MAKEFILE ####
# If you need to change these values for advanced 
# verification purposes, avoid using the "setup" targets of the makefile,
# as they will overwrite these parameters

# Flag for the random generation of the gnt signal (TCDM side)
RANDOM_GNT=0
# Flag to activate the priority handling check, where it is consider as LOW_PRIO_MAX_STALL the maximum number of consecutive stalls on low-priority channel.
PRIORITY_CHECK_MODE_ONE=1
# Flag to activate the priority handling check, where it is consider as LOW_PRIO_MAX_STALL the maximum number of consecutive cycles where there is at least 1 req both in the high and low priority channel
PRIORITY_CHECK_MODE_ZERO=0
# Maximum cycle offset: needed if you want to generate the list of the transaction with masters_main.py. It indicates the maximum number of clock cycles 
# between two consecutive requests coming from the same master. Note: the minimum value for this parameter is 1.
MAX_CYCLE_OFFSET=0